name: build-linux-clazy
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  QWT_version: 6.3.0

jobs:
  build-linux-clazy:
    # This build is only done on one Linux version as it is here only to get the warnings from clazy.
    # For other versions see build-linux.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install -y clazy apt-utils build-essential wget qt6-base-dev-tools qt6-declarative-dev qt6-multimedia-dev libqt6charts6-dev libqt6datavisualization6-dev libqt6svg6-dev libqt6core5compat6-dev libopencv-core-dev libopencv-dev libqwt-qt5-6 libqwt-qt5-dev libarmadillo-dev libgl1-mesa-dev libglu1-mesa-dev
      - run: wget -O qwt-6.3.0.zip https://sourceforge.net/projects/qwt/files/qwt/6.3.0/qwt-6.3.0.zip/download?use_mirror=pilotfiber
      - run: 7z x qwt-6.3.0.zip
      - run: cd qwt-6.3.0 ; /usr/lib/qt6/bin/qmake
      - run: cd qwt-6.3.0 ; make -j4
      - run: cd qwt-6.3.0 ; sudo make install
      - run: /usr/lib/qt6/bin/qmake  -spec linux-clang QMAKE_CXX="clazy"
      - uses: ammaraskar/gcc-problem-matcher@master
      # ignore noisy dirs from QT files itself
      # all level 1 checks but ignore clazy-no-connect-by-name
      # no parallel make with clazy to not mess log
      - run: export CLAZY_IGNORE_DIRS=".*usr.*|.*bezier.*|.*boost.*|.*SingleApplication.*|.*spdlog.*" && export CLAZY_CHECKS="level2,no-connect-by-name" && make
