name: build-linux
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - run: sudo apt install -y apt-utils build-essential wget
      - run: sudo apt install -y qt5-qmake qt5-qmake-bin qt5-assistant qtbase5-dev qtmultimedia5-dev
      - run: sudo apt install -y libqt5charts5 libqt5charts5-dev  libqt5multimedia*
      - run: sudo apt install -y libqt5datavisualization5-dev libqt5datavisualization5
      - run: sudo apt install -y libopencv-core-dev libopencv-core4.5d libopencv-dev
      - run: sudo apt install -y libqwt-qt5-6 libqwt-qt5-dev
      - run: sudo apt install -y libarmadillo-dev libarmadillo10
      - run: qmake
      - run: make
